# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    # Add steps to the job
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Setting up environment
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run lint!
          command: |
            . venv/bin/activate
            make lint

# Invoke jobs via workflows
workflows:
  build-workflow:
    jobs:
      - build
